const fs = require('fs');
const path = require('path');

const newChemicals = [
    {
        id: "chem-37",
        slug: "hidroklorik-asit",
        cas_number: "7647-01-0",
        formula: "HCl",
        category: "general",
        name_tr: "Hidroklorik Asit (Tuz Ruhu)",
        name_en: "Hydrochloric Acid",
        name_fr: "Acide Chlorhydrique",
        name_ar: "حمض الهيدروكلوريك",
        description_tr: "Halk arasında tuz ruhu olarak bilinen hidroklorik asit, kimya sanayisinde pH ayarlayıcı olarak, metalurjide pas sökücü olarak ve gıda sektöründe katkı maddesi üretiminde yaygın olarak kullanılan güçlü, aşındırıcı bir inorganik asittir.",
        description_en: "Commonly known as spirits of salt, hydrochloric acid is a strong, corrosive inorganic acid widely used in the chemical industry as a pH adjuster, in metallurgy as a rust remover, and in food additive production.",
        description_fr: "Acide inorganique fort et corrosif, largement utilisé dans l'industrie chimique pour ajuster le pH et en métallurgie.",
        description_ar: "حمض غير عضوي قوي ومسبب للتآكل يستخدم على نطاق واسع في الصناعة الكيميائية كمنظم لدرجة الحموضة وفي علم المعادن كمزيل للصدأ.",
        usage_areas_tr: ["Metal Temizleme (Dekapaj)", "pH Ayarlaması", "PVC Üretimi", "Evsel Temizlik (Tuz Ruhu)"],
        usage_areas_en: ["Metal Pickling", "pH Adjustment", "PVC Production", "Household Cleaning"],
        usage_areas_fr: ["Décapage des métaux", "Ajustement du pH", "Production de PVC", "Nettoyage domestique"],
        usage_areas_ar: ["تخليل المعادن", "تعديل درجة الحموضة", "إنتاج PVC", "التنظيف المنزلي"],
        ec_number: "231-595-7",
        molecular_weight: "36.46",
        synonyms_tr: "HİDROKLORİK ASİT=Tuz ruhu=Klorhidrik asit",
        synonyms_en: "HYDROCHLORIC ACID=Muriatic acid=Spirits of salt",
        definition_tr: ["Hidroklorik asit, hidrojen klorür (HCl) gazının suda çözünmesiyle oluşan renksiz (veya hafif sarımsı), oldukça tahriş edici ve dumanlı bir mineral asididir."],
        definition_en: ["Hydrochloric acid is a colorless (or slightly yellowish), highly irritating, and fuming mineral acid formed by dissolving hydrogen chloride (HCl) gas in water."],
        uses_benefits_tr: ["Asidik özelliği sayesinde karbonatlı bileşikleri (kireç gibi) hızla parçalar, bu nedenle en sert kireç ve pas lekelerinin çıkarılmasında etkilidir."],
        uses_benefits_en: ["Due to its acidic nature, it rapidly breaks down carbonate compounds (like scale), making it effective in removing the toughest limescale and rust stains."],
        applications_tr: ["Çelik endüstrisinde, galvanizleme veya haddeleme öncesinde metallerin üzerindeki pası (demir oksidi) temizlemek için (dekapaj banyosu) tonlarca kullanılır."]
    },
    {
        id: "chem-38",
        slug: "sodyum-tripolifosfat-stpp",
        cas_number: "7758-29-4",
        formula: "Na5P3O10",
        category: "general",
        name_tr: "Sodyum Tripolifosfat (STPP)",
        name_en: "Sodium Tripolyphosphate (STPP)",
        name_fr: "Tripolyphosphate de Sodium (STPP)",
        name_ar: "ترايبوليفوسفات الصوديوم (STPP)",
        description_tr: "Sodyum tripolifosfat, deterjan sanayisinde su yumuşatıcı olarak kullanılan ve tekstilde kalsiyum/magnezyum iyonlarını bağlayan inorganik bir polimerik fosfattır.",
        description_en: "Sodium tripolyphosphate is an inorganic polymeric phosphate used as a water softener in the detergent industry and to bind calcium/magnesium ions in textiles.",
        description_fr: "Phosphate polymérique inorganique utilisé comme adoucisseur d'eau dans l'industrie des détergents.",
        description_ar: "فوسفات بوليمري غير عضوي يستخدم كميسر للمياه في صناعة المنظفات لربط أيونات الكالسيوم والمغنيسيوم.",
        usage_areas_tr: ["Toz Deterjan Üretimi", "Su Yumuşatma", "Seramik Çamuru", "Gıda (Et Koruyucu)"],
        usage_areas_en: ["Powder Detergent Production", "Water Softening", "Ceramic Slurry", "Food (Meat Preservative)"],
        usage_areas_fr: ["Production de détergent en poudre", "Adoucissement de l'eau", "Boue céramique", "Alimentation (Viande)"],
        usage_areas_ar: ["إنتاج مسحوق المنظفات", "تيسير المياه", "ملاط السيراميك", "الأغذية (حفظ اللحوم)"],
        ec_number: "231-838-7",
        molecular_weight: "367.86",
        synonyms_tr: "SODYUM TRİPOLİFOSFAT=STPP=Penta-sodyum trifosfat",
        synonyms_en: "SODIUM TRIPOLYPHOSPHATE=STPP=Pentasodium triphosphate",
        definition_tr: ["STPP, trifosforik asidin sodyum tuzudur. Suda çok iyi çözünen, beyaz, kokusuz toz veya granül formunda bir inorganik katıdır."],
        definition_en: ["STPP is the sodium salt of triphosphoric acid. It is an inorganic solid in the form of a white, odorless powder or granule that dissolves very well in water."],
        uses_benefits_tr: ["Sert sulardaki iyonları şelatlama (içine hapsetme) yoluyla bağlayarak çökelmelerini engeller ve deterjandaki yüzey aktif maddelerin temizleme gücünü artırır."],
        uses_benefits_en: ["Binds ions in hard water through chelation (trapping), preventing their precipitation and increasing the cleaning power of surfactants in detergents."],
        applications_tr: ["Dünyadaki kullanımının %80'i deterjan sanayisindedir. Gıda endüstrisinde (E451) deniz ürünlerinde ve işlenmiş etlerde nemi hapsetmek için kullanılır."]
    },
    {
        id: "chem-39",
        slug: "sodyum-hekzametafosfat-shmp",
        cas_number: "10124-56-8",
        formula: "(NaPO3)6",
        category: "water-treatment",
        name_tr: "Sodyum Hekzametafosfat (SHMP)",
        name_en: "Sodium Hexametaphosphate (SHMP)",
        name_fr: "Hexamétaphosphate de Sodium",
        name_ar: "سداسي ميتافوسفات الصوديوم",
        description_tr: "SHMP, su arıtma sistemlerinde (Ters Osmoz) zar/membran tıkanmalarını önlemek için kullanılan, olağanüstü su yumuşatma (şelatlama) özelliğine sahip polimerik bir fosfattır.",
        description_en: "SHMP is a polymeric phosphate with exceptional water softening (chelating) properties, used in water treatment systems (Reverse Osmosis) to prevent membrane fouling.",
        description_fr: "Phosphate polymérique aux propriétés exceptionnelles d'adoucissement de l'eau, utilisé dans le traitement de l'eau (Osmose Inverse).",
        description_ar: "فوسفات بوليمري بخصائص استثنائية في تيسير المياه، يستخدم في أنظمة معالجة المياه (التناضح العكسي) لمنع انسداد الأغشية.",
        usage_areas_tr: ["Ters Osmoz (RO) Antiskalant", "Boya Endüstrisi (Dispersant)", "Gıda Katkısı (E452i)", "Seramik Sırları"],
        usage_areas_en: ["Reverse Osmosis (RO) Antiscalant", "Paint Industry (Dispersant)", "Food Additive (E452i)", "Ceramic Glazes"],
        usage_areas_fr: ["Antitartre pour Osmose Inverse", "Industrie de la peinture", "Additif alimentaire (E452i)", "Glaçures céramiques"],
        usage_areas_ar: ["مضاد للترسبات (RO)", "صناعة الطلاء", "مضافات غذائية (E452i)", "تزجيج السيراميك"],
        ec_number: "233-343-1",
        molecular_weight: "611.77",
        synonyms_tr: "SODYUM HEKZAMETAFOSFAT=SHMP=Kalgan",
        synonyms_en: "SODIUM HEXAMETAPHOSPHATE=SHMP=Calgon",
        definition_tr: ["SHMP, inorganik bir polifosfat halkasıdır. Suda çözündüğünde kompleks şelatlama zincirleri oluşturur."],
        definition_en: ["SHMP is an inorganic polyphosphate ring. When dissolved in water, it forms complex chelating chains."],
        uses_benefits_tr: ["Çok sert sularda bile kalsiyum ve magnezyum gibi mineralleri çözelti içinde tutarak (şelatlayarak) borularda ve membranlarda kireç taşı oluşumunu (scale) engeller."],
        uses_benefits_en: ["It keeps minerals like calcium and magnesium in solution (chelating) even in very hard water, preventing scale formation in pipes and membranes."],
        applications_tr: ["Sanayi tipi kazan sularının şartlandırılmasında antiskalant olarak ve kil/pigment süspansiyonlarında (boyalarda) dağıtıcı (dispersant) olarak görev alır."]
    },
    {
        id: "chem-40",
        slug: "amonyum-klorur",
        cas_number: "12125-02-9",
        formula: "NH4Cl",
        category: "general",
        name_tr: "Amonyum Klorür (Nişadır)",
        name_en: "Ammonium Chloride",
        name_fr: "Chlorure d'Ammonium",
        name_ar: "كلوريد الأمونيوم",
        description_tr: "Halk arasında 'Nişadır' olarak bilinen amonyum klorür, lehimlemede dekapaj (temizleme) ajanı olarak, tekstilde ve tarımda azot kaynağı olarak kullanılan asidik karakterli beyaz bir tuzdur.",
        description_en: "Known colloquially as 'sal ammoniac', ammonium chloride is a white, acidic salt used as a flux in soldering, and as a nitrogen source in textiles and agriculture.",
        description_fr: "Le chlorure d'ammonium est un sel blanc acide utilisé comme fondant de soudure et comme source d'azote dans l'agriculture.",
        description_ar: "كلوريد الأمونيوم (النشادر) ملح أبيض حمضي يستخدم كعامل تنظيف في اللحام، وكمصدر للنيتروجين في المنسوجات والزراعة.",
        usage_areas_tr: ["Lehimleme ve Kalaylama", "Tarım (Azotlu Gübre)", "Galvanizleme", "Kuru Piller"],
        usage_areas_en: ["Soldering and Tinning", "Agriculture (Nitrogenous Fertilizer)", "Galvanizing", "Dry Cell Batteries"],
        usage_areas_fr: ["Soudage et Étamage", "Agriculture (Engrais)", "Galvanisation", "Piles sèches"],
        usage_areas_ar: ["اللحام", "الزراعة (أسمدة نيتروجينية)", "الجلفنة", "البطاريات الجافة"],
        ec_number: "235-186-4",
        molecular_weight: "53.49",
        synonyms_tr: "AMONYUM KLORÜR=Nişadır=Amonyak tuzu",
        synonyms_en: "AMMONIUM CHLORIDE=Sal ammoniac=Salmiac",
        definition_tr: ["Amonyum klorür, amonyak ile hidroklorik asidin reaksiyonuyla elde edilen, suda kolay çözünen inorganik kristal formda bir katıdır."],
        definition_en: ["Ammonium chloride is an inorganic crystalline solid obtained by the reaction of ammonia with hydrochloric acid, easily soluble in water."],
        uses_benefits_tr: ["Isıtıldığında doğrudan gaz haline (süblimleşme) geçerken metal yüzeylerindeki oksit katmanlarını çözerek lehimin metale yapışmasını sağlar."],
        uses_benefits_en: ["When heated, it sublimes directly into gas while dissolving oxide layers on metal surfaces, allowing solder to adhere to the metal."],
        applications_tr: ["Çinko-karbon tipi kuru pillerin içinde elektrolit macunu olarak ve tekstilde boyama havuzlarında pH düşürücü (asitleştirici) olarak kullanılır."]
    },
    {
        id: "chem-41",
        slug: "sodyum-sulfit",
        cas_number: "7757-83-7",
        formula: "Na2SO3",
        category: "general",
        name_tr: "Sodyum Sülfit",
        name_en: "Sodium Sulfite",
        name_fr: "Sulfite de Sodium",
        name_ar: "كبريتيت الصوديوم",
        description_tr: "Sodyum sülfit, fotoğrafçılıkta, kağıt üretiminde ve su arıtmada klor giderici (oksijen tutucu) olarak kullanılan beyaz, suda çözünür bir inorganik tuzdur.",
        description_en: "Sodium sulfite is a white, water-soluble inorganic salt used in photography, paper production, and water treatment as an oxygen scavenger and antichlor.",
        description_fr: "Le sulfite de sodium est un sel inorganique soluble dans l'eau utilisé comme piégeur d'oxygène et antichlore dans le traitement de l'eau.",
        description_ar: "كبريتيت الصوديوم ملح غير عضوي أبيض قابل للذوبان في الماء يستخدم في التصوير الفوتوغرافي وإنتاج الورق ومعالجة المياه ككاسح للأكسجين.",
        usage_areas_tr: ["Kazan Suyu Şartlandırma", "Kağıt Hamuru (Sülfit Prosesi)", "Tekstil Antiklor", "Gıda Koruyucu"],
        usage_areas_en: ["Boiler Water Treatment", "Wood Pulp (Sulfite Process)", "Textile Antichlor", "Food Preservative"],
        usage_areas_fr: ["Traitement de l'eau des chaudières", "Pâte à papier", "Antichlore textile", "Conservateur alimentaire"],
        usage_areas_ar: ["معالجة مياه الغلايات", "لب الخشب (عملية الكبريتيت)", "مضاد للكلور في المنسوجات", "مادة حافظة للأغذية"],
        ec_number: "231-821-4",
        molecular_weight: "126.04",
        synonyms_tr: "SODYUM SÜLFİT=Sodyum sülföz",
        synonyms_en: "SODIUM SULFITE=Disodium sulfite",
        definition_tr: ["Sodyum sülfit (Na2SO3), güçlü indirgeyici özelliklere sahip sülfüröz asidin çözünebilir sodyum tuzudur."],
        definition_en: ["Sodium sulfite (Na2SO3) is a soluble sodium salt of sulfurous acid with strong reducing properties."],
        uses_benefits_tr: ["Suyun içinde çözünmüş olan oksijeni sülfata oksitlenerek tüketir; bu sayede buhar kazanlarında korozyonu (oksitlenmeyi) tamamen engeller."],
        uses_benefits_en: ["It consumes dissolved oxygen in water by oxidizing to sulfate, thereby completely preventing corrosion (oxidation) in steam boilers."],
        applications_tr: ["Tekstil sanayisinde kasar (ağartma) işleminden sonra kumaşta kalan klor kalıntılarını yok etmek için (antiklor ajanı) sıklıkla tercih edilir."]
    },
    {
        id: "chem-42",
        slug: "titanyum-dioksit",
        cas_number: "13463-67-7",
        formula: "TiO2",
        category: "general",
        name_tr: "Titanyum Dioksit",
        name_en: "Titanium Dioxide",
        name_fr: "Dioxyde de Titane",
        name_ar: "ثاني أكسيد التيتانيوم",
        description_tr: "Titanyum dioksit, dünyada bilinen en opak ve en beyaz madde olması nedeniyle boya, plastik, kozmetik ve kağıt sanayisinde kullanılan olağanüstü bir inorganik beyaz pigmenttir.",
        description_en: "Titanium dioxide is an extraordinary inorganic white pigment used in the paint, plastic, cosmetics, and paper industries as it is the most opaque and whitest substance known in the world.",
        description_fr: "Le dioxyde de titane est le pigment blanc inorganique le plus opaque au monde, utilisé dans la peinture, le plastique et les cosmétiques.",
        description_ar: "ثاني أكسيد التيتانيوم هو أكثر المواد المعتمة والبيضاء المعروفة في العالم، ويستخدم كصبغة بيضاء في صناعات الطلاء والبلاستيك ومستحضرات التجميل.",
        usage_areas_tr: ["Boya Endüstrisi", "Plastik ve Kauçuk", "Güneş Kremleri", "Gıda Boyası (E171)"],
        usage_areas_en: ["Paint Industry", "Plastics and Rubber", "Sunscreens", "Food Coloring (E171)"],
        usage_areas_fr: ["Industrie de la peinture", "Plastiques", "Crèmes solaires", "Colorant alimentaire (E171)"],
        usage_areas_ar: ["صناعة الطلاء", "البلاستيك والمطاط", "واقيات الشمس", "تلوين الأغذية (E171)"],
        ec_number: "236-675-5",
        molecular_weight: "79.87",
        synonyms_tr: "TİTANYUM DİOKSİT=Titanya=Pigment White 6 (PW6)",
        synonyms_en: "TITANIUM DIOXIDE=Titania=Pigment White 6 (PW6)",
        definition_tr: ["Titanyum dioksit (TiO2), doğada rutil, anataz ve brukit mineralleri olarak bulunan, ışığı kırma indisi elmastan bile daha yüksek olan bir bileşiktir."],
        definition_en: ["Titanium dioxide (TiO2) is a compound found in nature as rutile, anatase, and brookite minerals, with a refractive index higher than that of a diamond."],
        uses_benefits_tr: ["Gelen ışığı tamamen saçarak altındaki rengi (karanlığı) %100 kapatır. Boyalara mükemmel örtücülük (opaklık) kazandırır."],
        uses_benefits_en: ["It completely scatters incoming light, covering the color (darkness) beneath it 100%. It provides excellent hiding power (opacity) to paints."],
        applications_tr: ["İç ve dış cephe inşaat boyalarında beyazlığı veren tek ana faktördür. Kozmetikte UV ışınlarını bloke ettiği için fiziksel güneş koruyucuların etken maddesidir."]
    },
    {
        id: "chem-43",
        slug: "kukurtdioksit",
        cas_number: "7446-09-5",
        formula: "SO2",
        category: "general",
        name_tr: "Kükürt Dioksit",
        name_en: "Sulfur Dioxide",
        name_fr: "Dioxyde de Soufre",
        name_ar: "ثاني أكسيد الكبريت",
        description_tr: "Kükürt dioksit, sülfürik asit üretiminde ara ürün olarak, gıda endüstrisinde ise koruyucu ve antioksidan olarak kullanılan keskin kokulu zehirli bir gazdır.",
        description_en: "Sulfur dioxide is a toxic gas with a pungent odor, used as an intermediate in sulfuric acid production and as a preservative and antioxidant in the food industry.",
        description_fr: "Gaz toxique à l'odeur piquante, utilisé comme conservateur dans l'industrie alimentaire et comme intermédiaire chimique.",
        description_ar: "غاز سام ذو رائحة نفاذة، يستخدم كمادة وسيطة في إنتاج حمض الكبريتيك وكمادة حافظة ومضادة للأكسدة في صناعة الأغذية.",
        usage_areas_tr: ["Sülfürik Asit Sentezi", "Gıda Koruyucu (Şarapçılık)", "Kağıt Ağartma", "Dezenfeksiyon"],
        usage_areas_en: ["Sulfuric Acid Synthesis", "Food Preservative (Winemaking)", "Paper Bleaching", "Disinfection"],
        usage_areas_fr: ["Synthèse d'acide sulfurique", "Conservateur alimentaire (Vin)", "Blanchiment du papier", "Désinfection"],
        usage_areas_ar: ["تخليق حمض الكبريتيك", "مادة حافظة للأغذية (صناعة النبيذ)", "تبييض الورق", "التطهير"],
        ec_number: "231-195-2",
        molecular_weight: "64.07",
        synonyms_tr: "KÜKÜRT DİOKSİT=Sülfür dioksit",
        synonyms_en: "SULFUR DIOXIDE=Sulphur dioxide",
        definition_tr: ["Kükürt dioksit (SO2), kükürdün veya kükürt içeren yakıtların yanması sonucu açığa çıkan, renksiz, boğucu kokulu bir gazdır."],
        definition_en: ["Sulfur dioxide (SO2) is a colorless, suffocating gas released by the combustion of sulfur or sulfur-containing fuels."],
        uses_benefits_tr: ["Bakteri ve mantarların üremesini engelleyen çok güçlü bir antimikrobiyal ve oksitlenmeyi engelleyen bir indirgeyici ajandır."],
        uses_benefits_en: ["It is a very strong antimicrobial that prevents the growth of bacteria and fungi, and a reducing agent that prevents oxidation."],
        applications_tr: ["Kuru kayısı, incir gibi kuru meyvelerin kararmasını engellemek için (E220) tütsüleme işleminde ve şaraplarda fermantasyonu durdurmak için kullanılır."]
    },
    {
        id: "chem-44",
        slug: "baryum-sulfat",
        cas_number: "7727-43-7",
        formula: "BaSO4",
        category: "general",
        name_tr: "Baryum Sülfat",
        name_en: "Barium Sulfate",
        name_fr: "Sulfate de Baryum",
        name_ar: "كبريتات الباريوم",
        description_tr: "Baryum sülfat, yüksek yoğunluğu ve suda/asitte çözünmemesi nedeniyle petrol sondajlarında çamur ağırlaştırıcısı olarak ve tıpta X-ışını kontrast maddesi olarak kullanılan ağır bir mineraldir.",
        description_en: "Barium sulfate is a heavy mineral used as a mud weighting agent in oil drilling and an X-ray contrast agent in medicine due to its high density and insolubility in water/acid.",
        description_fr: "Le sulfate de baryum est un minéral lourd utilisé comme alourdissant de boue de forage et produit de contraste radiographique.",
        description_ar: "كبريتات الباريوم معدن ثقيل يستخدم كعامل تثقيل للطين في التنقيب عن النفط وعامل تباين للأشعة السينية في الطب بسبب كثافته العالية.",
        usage_areas_tr: ["Petrol ve Doğalgaz Sondajı", "Radyoloji (Tıp)", "Boya ve Plastik Dolgusu", "Fren Balataları"],
        usage_areas_en: ["Oil and Gas Drilling", "Radiology (Medicine)", "Paint and Plastic Filler", "Brake Pads"],
        usage_areas_fr: ["Forage pétrolier et gazier", "Radiologie (Médecine)", "Peinture et plastiques", "Plaquettes de frein"],
        usage_areas_ar: ["التنقيب عن النفط والغاز", "الأشعة (الطب)", "حشو الطلاء والبلاستيك", "تيل الفرامل"],
        ec_number: "231-784-4",
        molecular_weight: "233.39",
        synonyms_tr: "BARYUM SÜLFAT=Barit=Blanc fixe",
        synonyms_en: "BARIUM SULFATE=Barite=Blanc fixe",
        definition_tr: ["Baryum sülfat (BaSO4), doğada barit minerali olarak bulunan, olağanüstü derecede ağır, eylemsiz (inert) beyaz kristal formunda inorganik bir sülfat tuzudur."],
        definition_en: ["Barium sulfate (BaSO4) is an incredibly heavy, inert white crystalline inorganic sulfate salt found in nature as the mineral barite."],
        uses_benefits_tr: ["Suda ve asitte kesinlikle çözünmez. Toksik olmamasına rağmen, X-ışınlarını geçirmeme özelliğine sahiptir (radyopak)."],
        uses_benefits_en: ["Absolutely insoluble in water and acid. Although non-toxic, it is opaque to X-rays (radiopaque)."],
        applications_tr: ["Sondaj kuyularında petrolün veya gazın yukarı fışkırmasını engellemek için hidrostatik basıncı artırmak amacıyla sondaj çamurlarına devasa tonajlarda eklenir."]
    },
    {
        id: "chem-45",
        slug: "cinko-oksit",
        cas_number: "1314-13-2",
        formula: "ZnO",
        category: "general",
        name_tr: "Çinko Oksit",
        name_en: "Zinc Oxide",
        name_fr: "Oxyde de Zinc",
        name_ar: "أكسيد الزنك",
        description_tr: "Çinko oksit, kauçuk endüstrisinde vulkanizasyon aktivatörü, kozmetikte pişik kremi ve fiziksel UV filtresi olarak kullanılan inorganik beyaz bir tozdur.",
        description_en: "Zinc oxide is an inorganic white powder used as a vulcanization activator in the rubber industry, and as a diaper rash cream and physical UV filter in cosmetics.",
        description_fr: "L'oxyde de zinc est une poudre blanche inorganique utilisée dans l'industrie du caoutchouc, et comme filtre UV physique.",
        description_ar: "أكسيد الزنك مسحوق أبيض غير عضوي يستخدم كمنشط فلكنة في صناعة المطاط، وكريم لالتهاب الحفاضات وفلتر فيزيائي للأشعة فوق البنفسجية.",
        usage_areas_tr: ["Kauçuk Vulkanizasyonu", "Kozmetik (Güneş/Pişik Kremi)", "Seramik ve Cam", "Tıbbi Bantlar"],
        usage_areas_en: ["Rubber Vulcanization", "Cosmetics (Sun/Rash Creams)", "Ceramics and Glass", "Medical Tapes"],
        usage_areas_fr: ["Vulcanisation du caoutchouc", "Cosmétiques", "Céramique et Verre", "Rubans médicaux"],
        usage_areas_ar: ["فلكنة المطاط", "مستحضرات التجميل", "السيراميك والزجاج", "الأشرطة الطبية"],
        ec_number: "215-222-5",
        molecular_weight: "81.38",
        synonyms_tr: "ÇİNKO OKSİT=Çinko beyazı",
        synonyms_en: "ZINC OXIDE=Zinc white",
        definition_tr: ["Çinko oksit (ZnO), suda çözünmeyen, doğada çinkit minerali olarak bulunabilen ancak ticari olarak sentetik üretilen hafif, ince beyaz inorganik bir bileşiktir."],
        definition_en: ["Zinc oxide (ZnO) is an insoluble, light, fine white inorganic compound found in nature as zincite but produced synthetically for commerce."],
        uses_benefits_tr: ["Anti-bakteriyel ve anti-inflamatuar özellikleri sayesinde cilt tahrişlerini iyileştirir. Güneşin zararlı UVA ve UVB ışınlarını aynen yansıtır."],
        uses_benefits_en: ["Thanks to its anti-bacterial and anti-inflammatory properties, it heals skin irritations. It reflects the sun's harmful UVA and UVB rays like a mirror."],
        applications_tr: ["Dünyadaki kullanımının yarısından fazlası, otomobil lastiği üretiminde sülfürün kauçuğu sertleştirmesi (vulkanizasyon) işlemini aktive etmek için tüketilir."]
    },
    {
        id: "chem-46",
        slug: "potasyum-permanganat",
        cas_number: "7722-64-7",
        formula: "KMnO4",
        category: "water-treatment",
        name_tr: "Potasyum Permanganat",
        name_en: "Potassium Permanganate",
        name_fr: "Permanganate de Potassium",
        name_ar: "برمنجنات البوتاسيوم",
        description_tr: "Potasyum permanganat, tekstilde kot (denim) kumaşlara beyazlatma (ağartma) efekti vermek için, su arıtmada ise çok güçlü bir oksidan ve dezenfektan olarak kullanılan koyu mor kristal bir tuzdur.",
        description_en: "Potassium permanganate is a dark purple crystalline salt used in textiles to give a bleaching effect to denim fabrics, and in water treatment as a very strong oxidant and disinfectant.",
        description_fr: "Le permanganate de potassium est un sel cristallin violet foncé utilisé dans le textile (délavage du jean) et le traitement de l'eau.",
        description_ar: "برمنجنات البوتاسيوم ملح بلوري أرجواني داكن يستخدم في المنسوجات (تبييض الجينز) وفي معالجة المياه كمؤكسد ومطهر قوي جدا.",
        usage_areas_tr: ["Kot (Denim) Yıkama", "İçme Suyu Dezenfeksiyonu", "Tıbbi Dezenfektan", "Koku Giderme"],
        usage_areas_en: ["Denim Washing", "Drinking Water Disinfection", "Medical Disinfectant", "Odor Removal"],
        usage_areas_fr: ["Délavage du jean", "Désinfection de l'eau", "Désinfectant médical", "Élimination des odeurs"],
        usage_areas_ar: ["غسيل الدنيم (الجينز)", "تطهير مياه الشرب", "مطهر طبي", "إزالة الروائح"],
        ec_number: "231-760-3",
        molecular_weight: "158.03",
        synonyms_tr: "POTASYUM PERMANGANAT=Permanganik asit potasyum tuzu",
        synonyms_en: "POTASSIUM PERMANGANATE=Permanganic acid potassium salt",
        definition_tr: ["Potasyum permanganat (KMnO4), suda çözündüğünde çözeltiye çok yoğun bir mor-pembe renk veren, son derece güçlü oksitleyici özelliğe sahip inorganik bir bileşiktir."],
        definition_en: ["Potassium permanganate (KMnO4) is an inorganic compound with extremely strong oxidizing properties that imparts an intense purple-pink color to water when dissolved."],
        uses_benefits_tr: ["Demir, mangan ve sülfür hidrojen gibi kirleticileri anında oksitleyerek suda çökelmelerini (katılaşmasını) ve filtrelenmelerini sağlar."],
        uses_benefits_en: ["It instantly oxidizes pollutants like iron, manganese, and hydrogen sulfide, causing them to precipitate (solidify) in water and be filtered out."],
        applications_tr: ["Tekstil yıkama fabrikalarında kot pantolonlarda 'kullanılmış/yıpranmış' görünümünü elde etmek için (Rodeo efekti) kumaş yüzeyine lokal olarak uygulanır."]
    },
    {
        id: "chem-47",
        slug: "demir3-klorur",
        cas_number: "7705-08-0",
        formula: "FeCl3",
        category: "water-treatment",
        name_tr: "Demir(III) Klorür",
        name_en: "Ferric Chloride",
        name_fr: "Chlorure Ferrique",
        name_ar: "كلوريد الحديديك",
        description_tr: "Demir(3) klorür, endüstriyel atıksu ve kanalizasyon sularının arıtılmasında ağır metalleri ve fosfatı çöktürmek için kullanılan, elektronikte ise bakır plaket aşındırıcı olarak bilinen asidik bir koagülanttır.",
        description_en: "Ferric chloride is an acidic coagulant used to precipitate heavy metals and phosphate in industrial wastewater and sewage treatment, and is known as a copper etchant in electronics.",
        description_fr: "Le chlorure ferrique est un coagulant acide utilisé pour le traitement des eaux usées et pour graver les circuits imprimés.",
        description_ar: "كلوريد الحديديك هو مخثر حمضي يستخدم لترسيب المعادن الثقيلة والفوسفات في معالجة مياه الصرف الصناعي، ويُعرف كمحفر للنحاس في الإلكترونيات.",
        usage_areas_tr: ["Atıksu Arıtma (Koagülant)", "Baskılı Devre (PCB) Aşındırma", "Boya Endüstrisi", "Çamur Susuzlaştırma"],
        usage_areas_en: ["Wastewater Treatment (Coagulant)", "Printed Circuit Board (PCB) Etching", "Paint Industry", "Sludge Dewatering"],
        usage_areas_fr: ["Traitement des eaux usées", "Gravure de circuits (PCB)", "Industrie de la peinture", "Déshydratation des boues"],
        usage_areas_ar: ["معالجة مياه الصرف (مخثر)", "حفر لوحات الدوائر (PCB)", "صناعة الطلاء", "نزع الماء من الحمأة"],
        ec_number: "231-729-4",
        molecular_weight: "162.2",
        synonyms_tr: "DEMİR(III) KLORÜR=Ferrik klorür",
        synonyms_en: "FERRIC CHLORIDE=Iron(III) chloride",
        definition_tr: ["Ferrik klorür (FeCl3), genellikle %40'lık sulu çözelti halinde (koyu kahverengi/siyah sıvı) piyasada bulunan, yüksek oranda asidik ve korozif bir inorganik tuzdur."],
        definition_en: ["Ferric chloride (FeCl3) is a highly acidic and corrosive inorganic salt, usually found commercially as a 40% aqueous solution (dark brown/black liquid)."],
        uses_benefits_tr: ["Atıksudaki organik partiküllerin ve fosforun etrafını sararak (pıhtılaştırarak) ağır, çamur benzeri bir çökelti oluşturmalarını ve sudan ayrışmalarını sağlar."],
        uses_benefits_en: ["It surrounds (coagulates) organic particles and phosphorus in wastewater, causing them to form a heavy, sludge-like precipitate and separate from the water."],
        applications_tr: ["Belediye arıtma tesislerinde suların kokuşmasını engellemek (H2S gazını bağlamak) ve PCB üreten elektronik fabrikalarında gereksiz bakır yollarını eriterek devreyi ortaya çıkarmak için kullanılır."]
    },
    {
        id: "chem-48",
        slug: "bakir2-sulfat",
        cas_number: "7758-98-7",
        formula: "CuSO4",
        category: "general",
        name_tr: "Bakır(II) Sülfat (Göztaşı)",
        name_en: "Copper(II) Sulfate",
        name_fr: "Sulfate de Cuivre",
        name_ar: "كبريتات النحاس",
        description_tr: "Halk arasında Göztaşı olarak bilinen bakır sülfat, tarımda mantar öldürücü (fungisit) olarak, havuzlarda yosun önleyici (algisit) olarak kullanılan canlı mavi renkte bir tuzdur.",
        description_en: "Known colloquially as bluestone, copper sulfate is a vivid blue salt used as a fungicide in agriculture and an algaecide in pools.",
        description_fr: "Le sulfate de cuivre est un sel bleu vif utilisé comme fongicide en agriculture et algicide dans les piscines.",
        description_ar: "كبريتات النحاس ملح أزرق زاهٍ يستخدم كمبيد للفطريات في الزراعة ومبيد للطحالب في المسابح.",
        usage_areas_tr: ["Tarım (Bordo Bulamacı)", "Havuz Yosun Önleyici", "Yem Katkısı", "Metal Kaplama"],
        usage_areas_en: ["Agriculture (Bordeaux Mixture)", "Pool Algaecide", "Feed Additive", "Metal Plating"],
        usage_areas_fr: ["Agriculture (Bouillie bordelaise)", "Algicide pour piscine", "Additif alimentaire", "Placage métallique"],
        usage_areas_ar: ["الزراعة", "مبيد طحالب للمسابح", "مضافات علفية", "طلاء المعادن"],
        ec_number: "231-847-6",
        molecular_weight: "159.60",
        synonyms_tr: "BAKIR(II) SÜLFAT=Göztaşı=Göktaşı=Kuprik sülfat",
        synonyms_en: "COPPER(II) SULFATE=Cupric sulfate=Bluestone=Blue vitriol",
        definition_tr: ["Bakır sülfat (CuSO4), pentahidrat formu nedeniyle devasa ve son derece parlak mavi kristaller oluşturan, suda çözünebilen toksik bir inorganik bileşiktir."],
        definition_en: ["Copper sulfate (CuSO4) is a soluble, toxic inorganic compound that forms massive and extremely bright blue crystals due to its pentahydrate form."],
        uses_benefits_tr: ["Hücre zarlarını parçalayarak mantar, alg (yosun) ve kök zararlılarını anında öldürür. Aynı zamanda hayvan yemlerinde bakır minerali eksiğini giderir."],
        uses_benefits_en: ["Instantly kills fungi, algae, and root pests by disrupting their cell membranes. It also replenishes copper deficiency in animal feeds."],
        applications_tr: ["Kireç ile karıştırılarak (Bordo Bulamacı adıyla) zeytin, bağ ve meyve ağaçlarında kışlık mantar koruyucusu olarak tonlarca kullanılır."]
    },
    {
        id: "chem-49",
        slug: "dietanolamin-dea",
        cas_number: "111-42-2",
        formula: "C4H11NO2",
        category: "general",
        name_tr: "Dietanolamin (DEA)",
        name_en: "Diethanolamine (DEA)",
        name_fr: "Diéthanolamine",
        name_ar: "ثنائي إيثانول أمين",
        description_tr: "Dietanolamin, kozmetik deterjanlarda ve şampuanlarda köpük artırıcı olarak, tekstilde ise yumuşatıcı üretiminde kullanılan amonyak kokulu bir amino alkoldür.",
        description_en: "Diethanolamine is an amino alcohol with an ammonia odor used as a foam booster in cosmetic detergents and shampoos, and in the production of softeners in textiles.",
        description_fr: "La diéthanolamine est un amino-alcool utilisé comme exhausteur de mousse dans les shampooings et les détergents.",
        description_ar: "ثنائي إيثانول أمين كحول أميني يستخدم كمعزز للرغوة في الشامبو والمنظفات التجميلية، وفي إنتاج المنعمات في المنسوجات.",
        usage_areas_tr: ["Şampuan ve Deterjan (Köpürtücü)", "Tekstil Yumuşatıcıları", "Kozmetik (Emülgatör)", "Gaz Arıtma"],
        usage_areas_en: ["Shampoo and Detergents (Foaming Agent)", "Textile Softeners", "Cosmetics (Emulsifier)", "Gas Sweetening"],
        usage_areas_fr: ["Shampooings et détergents", "Adoucissants textiles", "Cosmétiques", "Purification de gaz"],
        usage_areas_ar: ["الشامبو والمنظفات (عامل رغوي)", "منعمات المنسوجات", "مستحضرات التجميل", "تنقية الغاز"],
        ec_number: "203-868-0",
        molecular_weight: "105.14",
        synonyms_tr: "DİETANOLAMİN=DEA=Bis(2-hidroksietil)amin",
        synonyms_en: "DIETHANOLAMINE=DEA=Bis(2-hydroxyethyl)amine",
        definition_tr: ["Dietanolamin (DEA), etilen oksit ve amonyağın reaksiyonundan üretilen, hem amin hem de alkol (hidroksil) özelliklerini aynı anda taşıyan ikincil bir amindir."],
        definition_en: ["Diethanolamine (DEA) is a secondary amine produced by the reaction of ethylene oxide and ammonia, possessing both amine and alcohol (hydroxyl) properties simultaneously."],
        uses_benefits_tr: ["Şampuan gibi temizlik ürünlerinde formülasyonu koyulaştırır (viskozite artırır) ve köpüğün kremsi, zengin yapıda olmasını sağlar."],
        uses_benefits_en: ["Thickens (increases viscosity) the formulation in cleaning products like shampoos and ensures the foam is creamy and rich."],
        applications_tr: ["Petrol rafinerilerinde asidik gazların (hidrojen sülfür) doğal gazdan ayrıştırılmasında sıvı absorban (gaz yıkayıcı) olarak kullanılır."]
    },
    {
        id: "chem-50",
        slug: "trietanolamin-tea",
        cas_number: "102-71-6",
        formula: "C6H15NO3",
        category: "general",
        name_tr: "Trietanolamin (TEA %85-%99)",
        name_en: "Triethanolamine (TEA)",
        name_fr: "Triéthanolamine",
        name_ar: "ثلاثي إيثانول أمين",
        description_tr: "Trietanolamin, asidik formülasyonları nötralize etmek (pH ayarlamak) için cilt kremlerinde, sıvı sabunlarda ve çimento sanayisinde öğütme kolaylaştırıcı olarak kullanılan viskoz bir kimyasaldır.",
        description_en: "Triethanolamine is a viscous chemical used to neutralize acidic formulations (adjust pH) in skin creams, liquid soaps, and as a grinding aid in the cement industry.",
        description_fr: "La triéthanolamine est utilisée pour neutraliser les formulations acides dans les cosmétiques et comme agent de mouture dans le ciment.",
        description_ar: "ثلاثي إيثانول أمين مادة كيميائية لزجة تستخدم لمعادلة التركيبات الحمضية في كريمات البشرة، والصابون السائل، وكمساعد طحن في صناعة الأسمنت.",
        usage_areas_tr: ["Cilt Kremleri (pH Düzenleyici)", "Sıvı Deterjan ve Sabun", "Çimento Öğütme Katkısı", "Metal İşleme Sıvıları"],
        usage_areas_en: ["Skin Creams (pH Adjuster)", "Liquid Detergent and Soap", "Cement Grinding Aid", "Metalworking Fluids"],
        usage_areas_fr: ["Crèmes pour la peau", "Détergent liquide", "Additif pour ciment", "Fluides de coupe"],
        usage_areas_ar: ["كريمات البشرة (منظم pH)", "المنظفات السائلة والصابون", "مساعد طحن الأسمنت", "سوائل تشغيل المعادن"],
        ec_number: "203-049-8",
        molecular_weight: "149.19",
        synonyms_tr: "TRİETANOLAMİN=TEA=Trolamin",
        synonyms_en: "TRIETHANOLAMINE=TEA=Trolamine",
        definition_tr: ["Trietanolamin (TEA), yağlılık hissi veren, renksizden soluk sarıya çalan renkte ve hafif amonyak kokulu tersiyer bir amin-alkol bileşiğidir."],
        definition_en: ["Triethanolamine (TEA) is a tertiary amine-alcohol compound that gives a greasy feel, ranging in color from colorless to pale yellow, with a mild ammonia odor."],
        uses_benefits_tr: ["Karışımlardaki (emülsiyon) yağ ve su fazlarını bir arada tutar. Çok yumuşak bir baz olduğu için kozmetiklerde cildi tahriş etmeden asitliği dengeler."],
        uses_benefits_en: ["Keeps oil and water phases together in mixtures (emulsions). Being a very mild base, it balances acidity in cosmetics without irritating the skin."],
        applications_tr: ["Karbomer bazlı el dezenfektanlarında ve jellerde jeli katılaştırıp (nötralize edip) şeffaflık vermek için 1-2 damla eklenmesi yeterlidir."]
    }
];

const dbPath = path.join(__dirname, '../src/data/chemicals.json');
const currentData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

const existingSlugs = currentData.map(c => c.slug);
const safeNewChemicals = newChemicals.filter(c => !existingSlugs.includes(c.slug));

const mergedData = [...currentData, ...safeNewChemicals];

fs.writeFileSync(dbPath, JSON.stringify(mergedData, null, 4), 'utf8');

console.log(`src/data/chemicals.json updated successfully. Added a massive batch of ${safeNewChemicals.length} items. Now contains ${mergedData.length} heavy chemicals!`);
